# This contains tasks to configure CLOS Leaf switches wth BGP and further show it
---
- name: Replace common Clos BGP CLI command template with leaf values
  template: src=clos_leaf_bgp_common.j2 dest=./commands/cnos_clos_leaf_{{ inventory_hostname }}_common_commands.txt
  with_items: "{{ cnos_clos_leaf_common_data }}"

- name: Applying common Clos BGP CLI commands to all leaf switches
  cnos_template: host={{ inventory_hostname }} commandfile=./commands/cnos_clos_leaf_{{ inventory_hostname }}_common_commands.txt username={{ hostvars[inventory_hostname][''ansible_ssh_user'']}}  password={{ hostvars[inventory_hostname]['ansible_ssh_pass']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} outputfile=./results/cnos_clos_leaf_{{ inventory_hostname }}_common_output.txt

- name: Replace unique Clos BGP CLI command template with unique leaf values for LP21
  template: src=clos_leaf_bgp_unique.j2 dest=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP21_commands.txt
  with_items: "{{ cnos_clos_leaf_LP21_data }}"

- name: Applying unique Clos BGP CLI commands to LP21 switch
  cnos_conditional_template: host={{ inventory_hostname }} commandfile=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP21_commands.txt username={{ hostvars[inventory_hostname]['ansible_ssh_user']}} password={{ hostvars[inventory_hostname]['ansible_ssh_pass']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} condition={{ hostvars[inventory_hostname]['condition']}} flag='{{item.flag}}' outputfile=./results/cnos_clos_leaf_{{ inventory_hostname }}_LP21_output.txt
  with_items: "{{ cnos_clos_leaf_LP21_data }}"

- name: Replace unique Clos BGP CLI command template with unique leaf values for LP22
  template: src=clos_leaf_bgp_unique.j2 dest=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP22_commands.txt
  with_items: "{{ cnos_clos_leaf_LP22_data }}"

- name: Applying unique Clos BGP  CLI commands to LP22 switch
  cnos_conditional_template: host={{ inventory_hostname }} commandfile=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP22_commands.txt username={{ hostvars[inventory_hostname]['ansible_ssh_user']}} password={{ hostvars[inventory_hostname]['ansible_ssh_pass']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} condition={{ hostvars[inventory_hostname]['condition']}} flag='{{item.flag}}' outputfile=./results/cnos_clos_leaf_{{ inventory_hostname }}_LP22_output.txt
  with_items: "{{ cnos_clos_leaf_LP22_data }}"

- name: Replace unique Clos BGP CLI command template with unique leaf values for LP23
  template: src=clos_leaf_bgp_unique.j2 dest=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP23_commands.txt
  with_items: "{{ cnos_clos_leaf_LP23_data }}"

- name: Applying unique Clos BGP CLI commands to LP23 switch
  cnos_conditional_template: host={{ inventory_hostname }} commandfile=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP23_commands.txt username={{ hostvars[inventory_hostname]['ansible_ssh_user']}} password={{ hostvars[inventory_hostname]['ansible_ssh_pass']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} condition={{ hostvars[inventory_hostname]['condition']}} flag='{{item.flag}}' outputfile=./results/cnos_clos_leaf_{{ inventory_hostname }}_LP23_output.txt
  with_items: "{{ cnos_clos_leaf_LP23_data }}"

- name: Replace unique Clos BGP CLI command template with unique leaf values for LP24
  template: src=clos_leaf_bgp_unique.j2 dest=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP24_commands.txt
  with_items: "{{ cnos_clos_leaf_LP24_data }}"

- name: Applying unique Clos BGP  CLI commands to LP24 switch
  cnos_conditional_template: host={{ inventory_hostname }} commandfile=./commands/cnos_clos_leaf_{{ inventory_hostname }}_LP24_commands.txt username={{ hostvars[inventory_hostname]['ansible_ssh_user']}} password={{ hostvars[inventory_hostname]['ansible_ssh_pass']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} condition={{ hostvars[inventory_hostname]['condition']}} flag='{{item.flag}}' outputfile=./results/cnos_clos_leaf_{{ inventory_hostname }}_LP24_output.txt
  with_items: "{{ cnos_clos_leaf_LP24_data }}"

- name: Replace CLOS BGP Leaf Switches CLI show template with values
  template: src=clos_leaf_bgp_show.j2 dest=./commands/cnos_clos_leaf_{{ inventory_hostname }}_show_commands.txt
  with_items: "{{ cnos_clos_leaf_show }}"

- name: Applying CLI show commands CLOS BGP Leaf Switches
  cnos_template: host={{ inventory_hostname }} commandfile=./commands/cnos_clos_leaf_{{ inventory_hostname }}_show_commands.txt username={{ hostvars[inventory_hostname]['ansible_ssh_user']}} password={{ hostvars[inventory_hostname]['ansible_ssh_pass']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} outputfile=./results/cnos_clos_leaf_{{ inventory_hostname }}_show_output.txt
  with_items: "{{ cnos_clos_leaf_show }}"

# Completed file
